services:
  - type: web
    name: pulso-piura-api-jesusmorales25
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /actuator/health
    autoDeployTrigger: commit
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: RENDER_DATABASE_URL
        fromDatabase:
          name: pulso-piura-demo-db
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: pulso-piura-demo-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: pulso-piura-demo-db
          property: password
      - key: AUTH_PROVIDER
        value: auth0
      - key: OIDC_ISSUER_URI
        sync: false
      - key: OIDC_AUDIENCE
        sync: false
      - key: OIDC_ROLES_CLAIM
        value: https://pulsopiura.app/roles
      - key: OIDC_CLAIMS_NAMESPACE
        value: https://pulsopiura.app
      - key: PLATFORM_ADMIN_EMAIL
        sync: false
      - key: WEB_ALLOWED_ORIGIN
        value: https://pulso-piura-platform.vercel.app
      - key: RESERVATION_HOLD_DURATION
        value: PT5M
      - key: RESERVATION_MAX_ACTIVE_TEMPORARY_PER_CUSTOMER
        value: "3"
      - key: PAYMENTS_MODE
        value: simulation
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "5"
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: "1"
      - key: JAVA_INITIAL_RAM_PERCENTAGE
        value: "15"
      - key: JAVA_MAX_RAM_PERCENTAGE
        value: "65"

databases:
  - name: pulso-piura-demo-db
    plan: free
    region: virginia
    databaseName: pulso_piura
    user: pulso_piura
    ipAllowList: []
