FROM quay.io/keycloak/keycloak:26.7.3 AS builder

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.7.3

COPY --from=builder /opt/keycloak/ /opt/keycloak/
USER root
COPY realm-pulso-piura.json /opt/keycloak/data/import/realm.json
COPY bootstrap.sh /opt/keycloak/bootstrap/bootstrap.sh
COPY render-entrypoint.sh /opt/keycloak/bootstrap/render-entrypoint.sh
COPY themes /opt/keycloak/themes
RUN chmod 0555 /opt/keycloak/bootstrap/bootstrap.sh /opt/keycloak/bootstrap/render-entrypoint.sh \
    && chown -R 1000:0 /opt/keycloak/data/import /opt/keycloak/bootstrap /opt/keycloak/themes
USER 1000

EXPOSE 10000
ENTRYPOINT ["/opt/keycloak/bootstrap/render-entrypoint.sh"]
